import { StyleSheet } from 'react-native';

const ConfigSectionStyles = StyleSheet.create({
  bottomConfigContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderColor: '#eee',
    zIndex: 10,
  },
  configToggle: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderColor: '#eee',
  },
  configToggleText: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#0366d6',
  },
  configSection: {
    backgroundColor: '#fff',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 8,
  },
  label: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#222',
  },
  dateInputRowNew: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 12,
    padding: 12,
    marginTop: 8,
    backgroundColor: '#f9fafd',
  },
  dateInputNew: {
    fontSize: 16,
    color: '#222',
    marginLeft: 10,
  },
  rowBetweenInline: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    marginTop: 18,
    marginBottom: 6,
  },
  daysStepperContainer: {
    flex: 1,
    marginRight: 8,
  },
  labelSmall: {
    fontSize: 13,
    color: '#222',
    marginBottom: 4,
    fontWeight: '500',
  },
  stepperRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f2f6fa',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    minWidth: 90,
    justifyContent: 'center',
  },
  stepperBtn: {
    padding: 4,
    borderRadius: 6,
    backgroundColor: '#e6f0fa',
    marginHorizontal: 4,
  },
  stepperValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#0366d6',
    marginHorizontal: 8,
  },
  stepperInput: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#0366d6',
    textAlign: 'center',
    minWidth: 40,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: '#fff',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#e6f0fa',
  },
  frequencyDropdown: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#f9fafd',
    minWidth: 110,
    justifyContent: 'space-between',
  },
  frequencyDropdownText: {
    fontSize: 15,
    color: '#222',
  },
  weekDaysRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 14,
    marginBottom: 2,
  },
  weekDayBtn: {
    borderWidth: 1,
    borderColor: '#0366d6',
    borderRadius: 18,
    paddingVertical: 6,
    paddingHorizontal: 12,
    marginHorizontal: 2,
    backgroundColor: '#fff',
  },
  weekDayBtnSelected: {
    backgroundColor: '#0366d6',
    borderRadius: 18,
    paddingVertical: 6,
    paddingHorizontal: 12,
    marginHorizontal: 2,
  },
  weekDayText: {
    color: '#0366d6',
    fontWeight: '500',
  },
  weekDayTextSelected: {
    color: '#fff',
    fontWeight: '500',
  },
  pillButtonRow: {
    flexDirection: 'row',
    marginTop: 10,
    marginBottom: 2,
    justifyContent: 'space-between',
  },
  pillBtn: {
    borderWidth: 1,
    borderColor: '#0366d6',
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 18,
    marginHorizontal: 2,
    backgroundColor: '#fff',
  },
  pillBtnSelected: {
    backgroundColor: '#0366d6',
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 18,
    marginHorizontal: 2,
  },
  pillBtnText: {
    color: '#0366d6',
    fontWeight: '500',
    fontSize: 15,
  },
  pillBtnTextSelected: {
    color: '#fff',
    fontWeight: '500',
    fontSize: 15,
  },
  instructionsInputNew: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 12,
    padding: 12,
    fontSize: 16,
    color: '#222',
    height: 100,
    marginTop: 6,
    textAlignVertical: 'top',
    backgroundColor: '#f9fafd',
  },
  saveBtn: {
    marginTop: 20,
    backgroundColor: '#0366d6',
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0366d6',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  saveBtnText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 18,
    letterSpacing: 0.2,
  },
  selectedItemIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#e6f0fa',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    marginBottom: 16,
    borderLeftWidth: 3,
    borderLeftColor: '#0366d6',
  },
  selectedItemText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#0366d6',
    marginLeft: 8,
  },
});

export default ConfigSectionStyles; 